version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cv_backend
    ports:
      - "8000:8000"
    volumes:
      - ./notebooks:/models  # Montage du dossier contenant cv_model_efficientNet.keras
    restart: always

  frontend:
    build: ./mobile_app
    container_name: cv_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
